
spring:
  profiles:
    active: local

# local 환경
---
spring:
  profiles:
    active: local
  datasource:
    data: classpath:data-h2.sql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true

